
source 'https://rubygems.org'

gem 'jekyll', '~> 4.0'

gem 'jekyll-theme-minimal'

title: EYES my ACAIS
description: A TIME CAPSULE
baseurl: "" 
url: "https://chandeshala.github.io"  
theme: jekyll-theme-minimal  
